project:
  type: website

website:
  title: "Xianghe's Blog Website"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/etc5523-2022/blog-xxuu0086
format:
  html:
    theme: cosmo
    css: styles.css



